export const IGNORE_TICKER = 'IGNORE_TICKER';
export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const RECONNECT_SOCKET = 'RECONNECT_SOCKET';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
export const SET_TIMER = 'SET_TIMER';
export const GET_TICKERS = 'GET_TICKERS';
