export const CONNECT_SOCKET = 'CONNECT_SOCKET';
export const DISCONNECT_SOCKET = 'DISCONNECT_SOCKET';
export const UPDATE_IGNORE_LIST = 'UPDATE_IGNORE_LIST';
export const UPDATE_TIMER = 'UPDATE_TIMER';
export const UPDATE_TICKERS = 'GET_TICKERS';
